// this file has been auto-generated by json2constants.py
#include "constants.h"

Constant g_constants[] = {
    {
       .name = "DISPLAY_HEIGHT",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 360
    },
    {
       .name = "DISPLAY_WIDTH",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 480
    },
    {
       .name = "ENTRY_POINT",
       .type = CONSTANT_TYPE_ADDRESS,
       .value = 1914696
    },
    {
       .name = "FIRST_FRAMEBUFFER_START",
       .type = CONSTANT_TYPE_ADDRESS,
       .value = 8008
    },
    {
       .name = "FLAGS",
       .type = CONSTANT_TYPE_REGISTER,
       .value = 253
    },
    {
       .name = "FRAMEBUFFER_SIZE",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 691200
    },
    {
       .name = "INSTRUCTION_POINTER",
       .type = CONSTANT_TYPE_REGISTER,
       .value = 254
    },
    {
       .name = "NUM_REGISTERS",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 256
    },
    {
       .name = "SECOND_FRAMEBUFFER_START",
       .type = CONSTANT_TYPE_ADDRESS,
       .value = 699208
    },
    {
       .name = "STACK_POINTER",
       .type = CONSTANT_TYPE_REGISTER,
       .value = 255
    },
    {
       .name = "STACK_SIZE",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 524288
    },
    {
       .name = "STACK_START",
       .type = CONSTANT_TYPE_ADDRESS,
       .value = 1390408
    },
    {
       .name = "TERMINAL_BUFFER_SIZE",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 8000
    },
    {
       .name = "TERMINAL_BUFFER_START",
       .type = CONSTANT_TYPE_ADDRESS,
       .value = 0
    },
    {
       .name = "TERMINAL_CURSOR_INDEX",
       .type = CONSTANT_TYPE_ADDRESS,
       .value = 8000
    },
    {
       .name = "TERMINAL_CURSOR_MODE",
       .type = CONSTANT_TYPE_ADDRESS,
       .value = 8004
    },
    {
       .name = "TERMINAL_CURSOR_MODE_BLINKING",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 0
    },
    {
       .name = "TERMINAL_CURSOR_MODE_INVISIBLE",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 2
    },
    {
       .name = "TERMINAL_CURSOR_MODE_VISIBLE",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 1
    },
    {
       .name = "TERMINAL_HEIGHT",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 25
    },
    {
       .name = "TERMINAL_WIDTH",
       .type = CONSTANT_TYPE_UNSIGNED_INTEGER,
       .value = 80
    },
};

size_t g_num_constants = sizeof(g_constants) / sizeof(g_constants[0]);
